services:
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      KAFKA_INGEST_COMMISSIONS_TASKS_TOPIC: stg-topic-tasks
      KAFKA_MART_COMMISSIONS_TOPIC: mart-topic-tasks
      KAFKA_PROCESS_DATA_TASKS_TOPIC: process-tasks
      KAFKA_CONSUMER_GROUP: topic-ingestors-stg
      KAFKA_BOOTSTRAP_SERVERS: kafka-compose-kafka-broker-1:9092
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ingests
      CLICKHOUSE_HOST: clickhouse
      CICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DB: default
    networks:
      - global

networks:
  global:
    external: true
